create table COCKTAIL_SHOPPING_LIST (
    COCKTAIL_ID UUID NOT NULL,
    SHOPPING_LIST_ID UUID NOT NULL,
    FOREIGN KEY (COCKTAIL_ID) REFERENCES COCKTAIL(ID),
    FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID),
    UNIQUE (COCKTAIL_ID, SHOPPING_LIST_ID)
);